export type EntityKind = "checkpoint" | "obstacle" | "npc";

export interface Rect { x: number; y: number; width: number; height: number; }
export interface Entity { id: string; kind: EntityKind; rect: Rect; label: string; color?: string | null; shape?: "circle" | "box" | "oriented-box"; rotation_degrees?: number; }
export interface Dynamics { model: "transient-bicycle-v1"; air_density_kg_m3: number; gravity_mps2: number; pixels_per_meter: number; physics_hz: number; control_hz: number; vehicle: {mass_kg: number; length_m: number; width_m: number; wheelbase_m: number; front_weight_fraction: number; center_of_mass_height_m: number; yaw_inertia_kg_m2: number; tire_friction_multiplier: number; drag_coefficient: number; lift_coefficient: number}; road: {friction_coefficient: number; lateral_grip_multiplier: number; rolling_resistance_multiplier: number}; }
export interface Scene { id: string; version: number; name: string; prompt: string; seed: number; bounds: Rect; player_spawn: {x: number; y: number}; start_line_index?: number; start_line_region?: string; player_grid_position?: number; entities: Entity[]; objectives: {kind: string; target_id: string; description: string}[]; domain_pack_version: string; track_centerline: {x: number; y: number}[]; track_width: number; edge_barriers?: boolean; laps: number; surface: "asphalt" | "clay" | "ice"; grip: number; npc_start_mode: "grid" | "distributed"; npc_behaviors: NpcBehavior[]; sector_count: number; dynamics: Dynamics; elevation?: ElevationSpec | null; track_report?: TrackReport | null; visual?: VisualPlan; }
/** Appearance only. The simulator never reads this, so a recolour cannot change a lap. */
export interface SceneryBand { label: string; color: string; region: string; orientation: "horizontal" | "vertical"; width_pixels: number; }
export interface VisualPlan { theme?: string; road?: string | null; terrain?: string | null; barrier?: string | null; player_car?: string | null; opponent_car?: string | null; kerbs?: boolean; kerb_light?: string | null; kerb_dark?: string | null; sky?: string | null; scenery?: SceneryBand[]; }
export interface NpcBehavior { entity_id: string; profile: "backmarker" | "cruiser" | "racer" | "aggressor" | "blocker"; pace: number; skill: number; aggression: number; defends: boolean; uses_nitro: boolean; }
export interface CornerReport { index: number; direction: "left" | "right"; requested_angle_degrees?: number | null; achieved_angle_degrees: number; requested_region: string; achieved_region: string; requested_radius: string; achieved_radius_pixels: number; entry_progress_percent: number; recommended_entry_speed: number; origin: "requested" | "closure-filler"; }
export interface TrackReport { compiler: string; direction: "clockwise" | "counterclockwise"; corners: CornerReport[]; length_pixels: number; longest_straight_pixels: number; minimum_radius_pixels: number; sector_count: number; closure_error_pixels: number; centerline_spacing_pixels: number; angle_fidelity_degrees: number; region_fidelity: number; relaxations: string[]; }
export interface ExperimentAddress { experiment: number; }
export interface EnvironmentAddress extends ExperimentAddress { environment: number; variant: number; }
export interface PlayerAddress extends EnvironmentAddress { player: number; }
export interface Environment { id: string; scene: Scene; created_at: string; validation: string[]; baseline_solved: boolean; parent_environment_id?: string | null; origin?: string | null; study_name?: string | null; address?: EnvironmentAddress | null; generator_provider?: string; generator_model?: string; generator_rationale?: string | null; generator_input_tokens?: number; generator_output_tokens?: number; generator_latency_ms?: number; playability_certificate?: { playable: boolean; checked_seed: number; objective_trace: string[]; route_steps: number; failure?: string | null } | null; prompt_spec?: PromptSpec | null; fidelity?: FidelityReport | null; }
export interface TrackDrawing { id: string; name: string; points: {x: number; y: number}[]; created_at: string; }
/** What the brief was read to be asking for, and whether the built circuit carries it.
 *  `quote` is the user's own words, so a miss can be reported back in them. */
export type RequirementCategory = "entity" | "layout" | "visual" | "dynamics" | "objective" | "constraint";
export interface RequirementCheck { kind: string; target: unknown; tolerance: number; }
export interface Requirement { id: string; category: RequirementCategory; statement: string; quote: string; priority: "must" | "should"; checks: RequirementCheck[]; }
export interface PromptSpec { prompt: string; requirements: Requirement[]; unspecified: string[]; unsupported: string[]; summary: string; }
export interface RequirementVerdict { id: string; category: string; statement: string; quote: string; priority: "must" | "should"; satisfied: boolean; method: "check" | "judge" | "unverifiable"; evidence: string; residual: number; claimed_at: string; }
export interface FidelityReport { verdicts: RequirementVerdict[]; judge_calls: number; }
export interface ArtifactLink { kind: "environment" | "run" | "study"; id: string; label: string; }
export interface AgentAction { id: string; label: string; state: StepState; logs: string[]; artifact?: ArtifactLink | null; }
export interface AgentMessage { id: string; agent_role: "main" | "environment"; environment_id?: string | null; speaker: "user" | "assistant"; content: string; created_at: string; artifacts: ArtifactLink[]; actions: AgentAction[]; }
export interface ProviderStatus { environment_generation: { active: string; openai_configured: boolean; anthropic_configured: boolean; active_environment_model: string; active_player_model: string; }; }
export interface ElevationSpec { profile: "flat" | "rolling" | "hilly" | "alpine"; amplitude_m: number; hill_count: number; banking_degrees: number; }
export type Dimensions = "2d" | "3d";
/** One coordinator turn. Everything but `summary` is absent when the turn was
 *  conversation — most turns are, and a reply that built nothing is still a real reply. */
export interface CoordinatorResult { summary: string; environment_id?: string | null; environment_name?: string | null; certificate?: { playable: boolean; objective_trace: string[]; route_steps: number } | null; }
export type StepState = "running" | "done" | "failed";
/** One newline-delimited event from a streaming endpoint. `token` is visible prose; the
 *  rest is work the harness did, which the UI keeps folded away until asked for. */
export type StreamEvent =
  | { type: "token"; text: string }
  | { type: "step"; id: string; label: string; state: StepState; artifact?: ArtifactLink }
  | { type: "progress"; scope: "experiment"; completed: number; total: number; elapsed_ms: number; eta_ms?: number | null; label: string }
  | { type: "log"; id: string; stage: string; detail: string }
  | { type: "done"; result?: CoordinatorResult; content?: string; artifacts?: ArtifactLink[]; run_ids?: string[] }
  | { type: "error"; detail: string };
export interface ProviderTurnUsage { turn: number; provider: string; model: string; input_tokens: number; output_tokens: number; output_budget: number; remaining_output_budget: number; latency_ms: number; }
export interface Frame { step: number; observation: {task: string; rgb_hint: string; proprioception: {x: number; y: number}; heading: number; speed: number; nitro: number; nitro_active: boolean; nitro_ready: boolean; countdown_ticks_remaining: number; longitudinal_speed_mps: number; lateral_speed_mps: number; yaw_rate_degrees_per_second: number; steering_angle_degrees: number; longitudinal_acceleration_mps2: number; lateral_acceleration_mps2: number; slip_angle_degrees: number; checkpoint_index: number; local_entities: {id: string; kind: string; distance: number; bearing?: number}[]}; privileged_state: {player: {x: number; y: number}; inventory: string[]; objective_index: number; heading: number; speed: number; nitro: number; nitro_active: boolean; nitro_ready: boolean; countdown_ticks_remaining: number; longitudinal_velocity_mps: number; lateral_velocity_mps: number; yaw_rate_degrees_per_second: number; steering_angle_degrees: number; longitudinal_acceleration_mps2: number; lateral_acceleration_mps2: number; slip_angle_degrees: number; aerodynamic_drag_n: number; rolling_resistance_n: number; lateral_load_transfer_n: number; turning: boolean; lap: number; barrier_impact?: {x: number; y: number} | null; entities: {id: string; kind: EntityKind; x: number; y: number; width: number; height: number; active: boolean; open: boolean; speed?: number; nitro?: number; nitro_active?: boolean; nitro_ready?: boolean; heading?: number; lane_offset?: number; track_index?: number; overtake_phase?: "cruise" | "passing" | "merge"}[]}; action: string; reward: number; events: string[]; decision?: {subgoal: string; confidence: number; summary: string; provider_usage?: ProviderTurnUsage | null}; }
export interface ResourceUsage { cpu_time_ms: number; wall_time_ms: number; max_rss_mb: number; gpu_memory_mb?: number | null; host?: string | null; }
export interface ArtifactReference { kind: string; uri: string; content_sha256: string; size_bytes: number; media_type: string; }
export interface ExecutionRecord { backend: string; state: "planned" | "queued" | "running" | "completed" | "failed" | "cancelled"; job_id?: string | null; resource_request: {cpu_cores: number; memory_mb: number; gpu_count: number; wall_time_seconds: number; queue?: string | null}; resource_usage?: ResourceUsage | null; scheduler_metadata: Record<string, unknown>; }
export interface ControllerWrite { tick: number; frame_step: number; effective_from_frame_step?: number | null; effective_until_frame_step?: number | null; wake: number; name: string; label?: string | null; source: string; reads: string[]; params: Record<string, unknown>; installed: boolean; active: boolean; errors: string[]; }
export interface Run { id: string; environment_id: string; policy_name: string; seed: number; status: "pending" | "running" | "succeeded" | "failed" | "timeout"; started_at: string; parent_run_id?: string | null; fork_step?: number | null; perturbation?: {kind: string; condition?: string | null; guidance?: string | null; summary?: string | null} | null; result_reason?: string | null; total_reward: number; token_usage: number; input_tokens?: number; output_tokens?: number; uncached_input_tokens?: number; cache_creation_input_tokens?: number; cache_read_input_tokens?: number; player_turns?: number; player_aggression?: number | null; output_token_budget?: number | null; latency_ms: number; study_name?: string | null; address?: PlayerAddress | null; execution: ExecutionRecord; artifacts: ArtifactReference[]; frames: Frame[]; controller_writes: ControllerWrite[]; fork_supported: boolean; guidance_supported: boolean; }
export interface ForkRequest { fork_step: number; condition?: string; perturbation?: "none" | "action_delay" | "obstacle_shift" | "low_grip" | "worn_tires" | "heavy_car" | "rear_bias" | "high_drag" | "high_downforce"; guidance?: string; }
export interface Experiment { id: string; name: string; address?: ExperimentAddress | null; environment_id: string; created_at: string; policies: string[]; perturbations: string[]; seeds: number[]; player_aggressions: number[]; run_ids: string[]; summary: {total_runs: number; rows: ExperimentRow[]; by_policy: Record<string, Aggregate>; by_perturbation: Record<string, Aggregate>}; }
export interface ExperimentRequest { environment_id: string; name?: string; policies: string[]; perturbations: string[]; seeds: number[]; max_steps: number; player_aggressions: number[]; }
export interface ExperimentRow { policy: string; perturbation: string; player_aggression?: number; environment_id: string; run_id: string; status: string; steps: number; reward: number; tokens: number; }
export interface Aggregate { count: number; success_rate: number; mean_steps: number; mean_reward: number; }
export interface StudyPanelManifest { id: string; title: string; description: string; kind: "metric" | "table"; version: string; }
export interface StudyPanelResult { id: string; title: string; kind: "metric" | "table"; summary: string; data: Record<string, unknown>; artifacts: ArtifactLink[]; }
export interface StudyPanelDashboard { configuration: { study_kind: "comparison"; study_id: string; panel_ids: string[] }; catalog: StudyPanelManifest[]; panels: StudyPanelResult[]; }
